# MySQL
# https://blog.csdn.net/weixin_41753316/article/details/109241842
docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=你的密码 -d mysql:5.7
docker exec -it mysql bash
mysql -h localhost -u root -p
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '密码' WITH GRANT OPTION;


# Redis
docker run --name redis -it -p 6379:6379 -v /data/redis-data  redis --requirepass "123456"


# RabbitMQ
# https://blog.csdn.net/niugang0920/article/details/109496832
docker pull rabbitmq:management
docker run -dit --name Myrabbitmq -e RABBITMQ_DEFAULT_USER=admin -e RABBITMQ_DEFAULT_PASS=admin -p 15672:15672 -p 5672:5672 rabbitmq:management


# Nacos
# https://www.bilibili.com/video/BV11R4y1K7jJ
  docker run -d -p 8848:8848 -p 9848:9848 -p 9849:9849 \
    > --restart=always \
    > -e MODE=standalone \
    > -e MYSQL_SERVICE_PORT=3306 \
    > -e MYSQL_SERVICE_USER=root \
    > -e MYSQL_SERVICE_DB_NAME=nacos \
    > -e MYSQL_SERVICE_PASSWORD=root \
    > -e SPRING_DATASOURCE_PLATFORM=mysql \
    > -e MYSQL_SERVICE_HOST=192.168.1.5 \
    > --name nacos nacos/nacos-server:2.0.3
# 后续对nacos配置更改指令
# https://blog.csdn.net/dumuzhouguohe/article/details/123390684
docker exec -it nacos bash



# sentinel dashboard
docker pull docker.io/bladex/sentinel-dashboard

docker run --restart=always \
--name sentinel \
-d -p 8858:8858 -d bladex/sentinel-dashboard


